apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: marcuszeitsch-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: app-backend
          image: ghcr.io/zeitschmarcus92/kukuk-app-backend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
