apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: marcuszeitsch-prod
  labels: { app: app-backend }
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector: { matchLabels: { app: app-backend } }
  template:
    metadata: { labels: { app: app-backend } }
    spec:
      containers:
        - name: app-backend
          image: REGISTRY_URL/app-backend:TAG
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: marcuszeitsch-prod
spec:
  selector: { app: app-backend }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
