apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: marcuszeitsch-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: app-backend
          image: ghcr.io/zeitschmarcus92/kukuk-app-backend:dev
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
