apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: marcuszeitsch-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: app-frontend
          image: ghcr.io/zeitschmarcus92/kukuk-app-frontend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_URL
