apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: marcuszeitsch-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: ghcr.io/zeitschmarcus92/kukuk-app-frontend:prod-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
