apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: marcuszeitsch-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: app-frontend
          image: ghcr.io/zeitschmarcus92/kukuk-app-frontend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_URL
